language: python
os: linux
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - "pip install -r requirements.txt"
      # the -e is most necessary, else Coverage.py warning: No data was collected. (no-data-collected)
      # Causing coveralls.io to fail
    - "pip install -e ."
    - "pip install pytest"
    - "pip install pytest-cov"
    # - "pip install coverage"
    - "pip install coveralls"
script:
    - "pytest"
    # - "coverage run --source=Afvaldienst setup.py test"
    - "py.test --cov-report term-missing --cov=Afvaldienst tests/"
    # - "py.test --cov=Afvaldienst tests/"
after_success: coveralls
